// Upstream-sync dry-run — the OFFLINE rehearsal of the §7.2 sync bot.
//
// The real §7.2 flow is: scheduled Action → fetch upstream/dev → create sync
// branch → classify the diff (§7.3) → run each route's verification → open an
// auto-PR that bumps the `vendor/PathOfBuilding-PoE2` submodule pointer and
// attaches a per-route test report. Two of those steps touch the network — the
// `git fetch` and the PR `open` — and are gated behind a human "network" gate.
//
// This dry-run reproduces everything EXCEPT those two networked steps. It reads a
// COMMITTED fixture changed-files list (no live fetch, no remote), runs the §7.3
// classifier on it, renders the routed-verification report, and synthesizes the
// PR body the bot WOULD open — with the fetch/open steps replaced by explicit,
// labelled stubs. It is pure and deterministic and always exits 0. This lets the
// §7.2 wiring be tested in CI without a network or credentials.

import { readFileSync } from 'node:fs';
import { classifyDiff, ROUTES, UNKNOWN } from './classify.mjs';

/**
 * @typedef {object} ChangedFilesFixture
 * @property {string} submodule - the submodule path whose pointer the PR bumps.
 * @property {string} [branch]  - the upstream branch being tracked.
 * @property {string} from      - current pinned commit SHA (pointer "before").
 * @property {string} to        - candidate upstream SHA (pointer "after").
 * @property {string[]} files   - vendor-relative POSIX paths changed between them.
 */

/**
 * Load and validate the committed changed-files fixture. This is the ONLY input;
 * there is no git or network access anywhere in this module.
 *
 * @param {string} path - absolute path to the fixture JSON.
 * @returns {ChangedFilesFixture}
 */
export function loadFixture(path) {
  const fixture = JSON.parse(readFileSync(path, 'utf8'));
  for (const key of ['submodule', 'from', 'to']) {
    if (typeof fixture[key] !== 'string' || fixture[key].length === 0) {
      throw new Error(`changed-files fixture missing string field "${key}"`);
    }
  }
  if (!Array.isArray(fixture.files)) {
    throw new Error('changed-files fixture "files" must be an array');
  }
  return fixture;
}

/**
 * Render the routed-verification report: for each fired §7.3 route, the route id,
 * what it verifies, and the changed paths that triggered it; then the unknown
 * bucket (surfaced for manual triage, never hidden).
 *
 * @param {import('./classify.mjs').DiffClassification} classification
 * @returns {string}
 */
export function buildReport(classification) {
  const lines = ['Routed verification report (DESIGN §7.3)', ''];
  for (const route of classification.routesTriggered) {
    const meta = ROUTES[route];
    lines.push(`- ${route}: ${meta.description}`);
    lines.push(`  manual review: ${meta.manualReview}`);
    for (const path of classification.routes[route]) {
      lines.push(`    • ${path}`);
    }
  }
  if (classification.hasUnknown) {
    lines.push('');
    lines.push(`- ${UNKNOWN}: no §7.3 rule matched — requires manual triage`);
    for (const path of classification.unknown) {
      lines.push(`    • ${path}`);
    }
  }
  return lines.join('\n');
}

/**
 * Synthesize the PR body the §7.2 sync bot would open. Two sections per DESIGN
 * §7.2: (1) the submodule pointer bump (from → to SHA), and (2) the per-route
 * test report. The PR is NOT opened here — that step is network-gated and stubbed.
 *
 * @param {ChangedFilesFixture} fixture
 * @param {import('./classify.mjs').DiffClassification} classification
 * @returns {string}
 */
export function buildPrBody(fixture, classification) {
  const branch = fixture.branch ? ` (${fixture.branch})` : '';
  const lines = [
    `chore(upstream-sync): bump ${fixture.submodule} to ${fixture.to.slice(0, 12)}`,
    '',
    '## Submodule pointer bump',
    '',
    `- submodule: \`${fixture.submodule}\`${branch}`,
    `- from: \`${fixture.from}\``,
    `- to:   \`${fixture.to}\``,
    '',
    '## Per-route test report',
    '',
  ];
  for (const route of classification.routesTriggered) {
    const meta = ROUTES[route];
    const n = classification.routes[route].length;
    lines.push(`- \`${route}\` — ${meta.description} (${n} file${n === 1 ? '' : 's'})`);
  }
  if (classification.hasUnknown) {
    lines.push(`- \`${UNKNOWN}\` — ${classification.unknown.length} path(s) need manual triage`);
  }
  lines.push('');
  lines.push('> Generated by `upstream-sync dry-run`. The live `git fetch` and the');
  lines.push('> PR `open` are network-gated and stubbed in dry-run — nothing was');
  lines.push('> fetched and no PR was opened.');
  return lines.join('\n');
}

/**
 * @typedef {object} DryRunResult
 * @property {import('./classify.mjs').DiffClassification} classification
 * @property {string} report
 * @property {string} prBody
 * @property {{ fetched: boolean, prOpened: boolean }} network - both always false
 *   in dry-run; the networked steps are gated and stubbed, never executed.
 * @property {number} exitCode
 */

/**
 * Run the offline dry-run end to end on an already-loaded fixture. Pure: no git,
 * no network, no writes. Always exits 0 (the routed report is informational; the
 * sync bot decides what to do with unknowns).
 *
 * @param {ChangedFilesFixture} fixture
 * @returns {DryRunResult}
 */
export function runDryRun(fixture) {
  const classification = classifyDiff(fixture.files);
  return {
    classification,
    report: buildReport(classification),
    prBody: buildPrBody(fixture, classification),
    network: { fetched: false, prOpened: false },
    exitCode: 0,
  };
}

import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

// CLI: `node src/dry-run.mjs` (registered as @pob2/upstream-sync `dry-run`).
if (import.meta.url === `file://${process.argv[1]}`) {
  const here = dirname(fileURLToPath(import.meta.url));
  const fixturePath = resolve(here, '../fixtures/changed-files.json');
  const fixture = loadFixture(fixturePath);
  const r = runDryRun(fixture);

  console.log('=== upstream-sync dry-run (offline; DESIGN §7.2) ===');
  console.log(`fixture: ${fixturePath}`);
  console.log(
    `network: fetch=${r.network.fetched ? 'live' : 'stubbed'} ` +
      `openPR=${r.network.prOpened ? 'live' : 'stubbed'} (humanGate: network)`,
  );
  console.log('');
  console.log(r.report);
  console.log('');
  console.log('=== synthetic PR body ===');
  console.log('');
  console.log(r.prBody);

  process.exit(r.exitCode);
}
